---
require:
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  MaxFilesInCache: 2048
  TargetRubyVersion: 2.6
  UseCache: true
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/MethodLength:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
